# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9daa05005120c403a1becfbf9e3f32b480456f6e3493133ba0ad64800bf8e68180dcee1d075f3037380abb376f1766ae4295959d6838d54c95ac772cbe3c9a9f

test:
  secret_key_base: 73dae1c1258f9aac5e670914fda49a1a0caa38d565c39bb007c76d8fc8be9a2fa1e24c214f56bede0d7e87c92760ec2b9efc59b5d30bad599c154815ba1a37de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
